module.exports = (config) ->
  config.set
    basePath: ''
    frameworks: [
      'jasmine'
    ]
    files: [
        '../bower_components/angular/angular.js'
        '../bower_components/angular-animate/angular-animate.js'
        '../bower_components/angular-aria/angular-aria.js'
        '../bower_components/angular-cookies/angular-cookies.js'
        '../bower_components/angular-messages/angular-messages.js'
        '../bower_components/angular-resource/angular-resource.js'
        '../bower_components/angular-sanitize/angular-sanitize.js'
        '../bower_components/angular-touch/angular-touch.js'
        '../bower_components/angular-route/angular-route.js'
        '../bower_components/angular-mocks/angular-mocks.js'
        '../.tmp/**/*.js'
    ]
    exclude: [
        '**/index.js'
    ]
    reporters: [ 'dots' ]
    port: 9876
    colors: true
    logLevel: config.LOG_INFO
    autoWatch: true
    browsers: [ 'PhantomJS' ]
    singleRun: false
    concurrency: Infinity
  return

# ---
# generated by js2coffee 2.1.0
